POST localhost:8080/order_products/create
Content-Type: application/json

{
  "order": {
    "id": 1
  },

  "product": {
    "id": 3

  },
  "quantity": 2,
  "price_per_unit": 10

}




GET localhost:8080/customer/1


POST localhost:8080/createOrder
Content-Type: application/json

{
"location": {
"id": 1
},

"dateTime": "2023-12-07",
"deliveryAddress": "blabla",
"deliveryMan": "man"
}


DELETE localhost:8080/location/delete/1

POST localhost:8080/manager/create
Content-Type: application/json

{
  "location": {
    "id": 1
  },


  "firstName": "Mr",
  "lastName": "W" ,
  "address": "123add",
  "salary": 20000
}

POST localhost:8080/createOrder
Content-Type: application/json

{
  "location": {
    "id": 1
  },

  "dateTime": "2023-12-07",
  "deliveryAddress": "blabla",
  "deliveryMan": "man"
}




