POST localhost:8080/onlineorder/create
Content-Type: application/json

{
  "location": {
    "id": 1
  },
  "customer": {
    "id": 1
  },
  "date_time": "2023-12-07",
  "delivery_address": "blabla",
  "delivery_man": "man"
}




