DELETE localhost:8080/event/delete/2

POST localhost:8080/event/create
Content-Type: application/json

{
  "name": "ssmi",
  "host": ".msg",
  "profit": 100000.0
}

PUT localhost:8080/event/setLocation/1/1


